### PR TITLE
ToTV Tracker

### PR DESCRIPTION
**Pull request by markus101**
@Taloth Replaces PR https://github.com/Sonarr/Sonarr/pull/234 I ended up redoing it all because the existing PR was out of date and had a bunch of awkward commits.

### CODE REVIEW

**Comment by level42ca** [comment]
Glad to see there are still signs of life for this. Thanks to all who are working on this.

**Comment by Terebi42** [comment]
Sorry for the lack of communication. This PR won't work, the ToTV API has changed, I hadn't put in a new PR yet, because there is still some risk of API changes and I didn't want to have things break for users unexpextedly.

**Comment by markus101** [comment]
@Terebi42 I had to make a couple changes to get it working, but it does seem to be working. Any idea when those changes might go through?

**Comment by Terebi42** [comment]
See PR 656

**Comment by Fossil01** [comment]
Anyone got an invite to this site so I can check it out?

**Comment by level42ca** [comment]
Just checking in, wondering how progress is coming along.

**Comment by Whovian9369** [comment]
Adding in my "Please"

**Comment by AzzAToTV** [comment]
Thanks for your work @Taloth  :)

**Comment by Taloth** [comment]
Just a heads up, we've been doing maintenance on our CI build servers, so it's not actually released yet.

Also there are a few things on the api that need improvement, but I figured we would first get it released so we can get a good idea of what's missing.
(Since the master release a week ago I've been working on getting several PRs merged in, was way overdue.)

**Comment by AzzAToTV** [comment]
Alright no worries, just tag me or @Terebi42 if you need anything :)

**Pull request merged**
