### PR TITLE
New: sequential download option for qBittorrent

### PR DESCRIPTION
**Pull request by mickael9**
#### Database Migration
NO

#### Description
Adds an advanced option to use sequential downloads for qBittorrent

### CODE REVIEW

**Comment by markus101** [comment]
What's the advantage of downloading sequentially/why should Sonarr support it?

**Comment by mickael9** [comment]
Hi, the advantage is that you can start watching while the download is still in progress.

The option is shown as a check box in qBittorrent when manually adding a new torrent, so I think it's reasonable to have the option to enable it for Sonarr-initiated downloads.

image

**Comment by bakerboy448** [comment]
Sonarr won't import it until its complete though and you really shouldn't be printing plex at your downloads folder

**Comment by mickael9** [comment]
I agree, but I don't use Plex. I just point mpv directly to the file I want to watch.
It's probably not the most common use case which is why I put it as an advanced option but I don't think there is any harm in having it

**Comment by markus101** [comment]
We’ve discussed this and it’s not something we plan to support on qbit or other clients. A custom script that talks to the qbit API after its added by Sonarr is your best bet to achieve Hugo’s.

**Pull request closed without merging**
