### PR TITLE
Title case buttons

### PR DESCRIPTION
**Pull request by Thirrian**
Updates all buttons to title case for consistency, see also https://trello.com/c/LVVbmp0z

### CODE REVIEW

**Comment by Taloth** [comment]
I suspect we had ```text-transform : capitalize;``` on Bootstrap2 stylesheets a year ago.
See https://github.com/Sonarr/Sonarr/commit/99f2b07a115bb4ca2b2ce0a76baf38d66a6c5cef#diff-c9e426bd44bc4c4268961bf4647a0272L19

@markus101 Add again to our override stylesheet? Or edit every page to capitalize manually?

**Comment by Thirrian** [comment]
I suppose that is a more sane approach rather than updating each and every button. You youngsters and your fancy CSS. Back in my day we had just invented URL's and we were happy :smile:

**Comment by markus101** [comment]
@Taloth yeah, looks like it. I think we should add the override.

@Thirrian has already done the work and I think we should merge it, if only to not waste his time, but also because then its clear what it should look like in the event someone else comes along and adds a button.

@Thirrian could you squash (http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) `git rebase -i HEAD~2` should get you started.

**Comment by Thirrian** [comment]
I think I botched this... :disappointed:

**Comment by markus101** [comment]
Yup! But it can be fixed.

First would be to hard reset you changes back before the merge of Sonarr/Sonarr into your branch, then do the interactive rebase to squash the two commits into 1. Then rebase off of Sonarr/Sonarr's develop branch.

**Comment by Thirrian** [comment]
Still lost :(

    git reset --hard 6f70db1
    git rebase -i HEAD~2
All the changes in a single commit, looking good...
Then:

    git rebase Sonarr/develop

Okay, this seems to be what I want, pull changes from Sonarr/develop, then replay my changes on top of it... This is where I get lost. This seemed like the way to go:

    git push origin title-case
But this results in:

    Updates were rejected because the tip of your current branch is behind its remote counterpart. Integrate the remote changes (e.g. 'git pull ...') before pushing again. See the 'Note about fast-forwards' in 'git push --help' for details.

Now I'm looking at 10.000 guides all telling me to do different things to fix this particular issue, but as you can see it's screwed up again :cry:
Thanks for the patience though, I'll get there I guess...

**Comment by Taloth** [comment]
You're getting close. :smile: 

After squashing you usually have to force-push, overwriting what's in the remote repository:
```git push --force origin title-case```

**Comment by Thirrian** [comment]
Oh my. --force is all it took.
Thanks so much @markus101 and @Taloth for the patience explaining a newbie!

**Comment by Taloth** [comment]
Btw. Personally I use GitExtensions for Windows, doing stuff graphically is sometimes easier.

**Pull request merged**
