### PR TITLE
Diskstation: Fix for key not found, returning a generic error instead

### PR DESCRIPTION
**Pull request by margaale**
#### Database Migration
NO

#### Description
Returns a generic error message if error-code is not in the dictionary.

#### Issues Fixed or Closed by this PR
#1700

### CODE REVIEW

**Comment by Taloth** [comment]
Another user has authentication issues. Must something be set on the download station for auth to work on the api? https://www.reddit.com/r/sonarr/comments/5vdxdn/sonarr_v2004613_and_btn_update/de2aqe0/
If so, then clarifying that in the Test ValidationError would be a good idea.

**Comment by Taloth** [comment]
And another, which is a significant bug: https://forums.sonarr.tv/t/synology-download-station-ssl-sonarr-v2-0-0-4613/13779

**Comment by margaale** [comment]
1) Not aware that any special configuration should be done.
2) That seems pretty bad, "type string Possible types: BT, NZB, http, ftp, eMule 1 and later" taken from https://global.download.synology.com/download/Document/DeveloperGuide/Synology_Download_Station_Web_API.pdf page 28. Guess they didn't include it in the list. I' gonna submit a patch right now.

**Comment by Taloth** [comment]
Maybe the api object should be a string, that way we can handle new ones.

**Comment by margaale** [comment]
Yeah, thats's a good idea...

**Comment by margaale** [comment]
Done

**Comment by Taloth** [comment]
Missing one thing: A unittest.  But i'll take that on and merge to dev.

**Comment by margaale** [comment]
Ha, sorry, i'm at work now. No much time...

**Comment by Taloth** [comment]
It was a 'little' bit more involved than I wanted, but I think I made the right choice.
I pulled out the filter from the proxy, it didn't really belong there coz proxy needs to be as thin as possible. That allowed me to add the appropriate tests to Torrent/UsenetDownloadStation.

**Comment by margaale** [comment]
Yep, that was my next step. But i had no time now to do it. Thanks

**Pull request merged**
