### PR TITLE
Updated OS X startup script to work with macports mono

### PR DESCRIPTION
**Pull request by GavinJS**

### CODE REVIEW

**Comment by markus101** [comment]
@GavinJS could you clarify what the advantage of this change is? Saves the user from installing mono a second time if it already exists via another installation method?

**Comment by GavinJS** [comment]
@markus101 yes that's correct...  If you install Mono via the MacPorts package manager it installs everything into the default location of /opt so the Sonarr startup script always fails because it's hard coded to use the libs in the Mono framework downloadable package.

**Comment by ugokanain** [comment]
Was this change incorporated and then dropped? I also use macports, and Gavin's change is working fine

Please added to the mac version

**Comment by kayone** [comment]
Merged into develop. 
Thanks!

**Pull request closed without merging**
