### PR TITLE
Import and Rename Extra files

### LINKED ISSUE #459: Move Additional Files
Opt-in to move nfo, sfv, etc - we will need to keep the files named properly after a rename.

### PR DESCRIPTION
**Pull request by markus101**
#### Database Migration
NO

#### Description
Importing of extra files (new option in the UI) and renaming them when the episode file is renamed.

#### Issues Fixed or Closed by this PR

Closes #459

### CODE REVIEW

**Comment by dwatley** [comment]
What's the status here? Seems like #459 is on the cusp of being completed and it's much needed.

**Comment by KalleDK** [comment]
Looking forward for this feature 💛 Is about to move my whole library, but I really dont want to move the srt's manually

**Comment by valantislevas** [comment]
any news about ?

**Comment by markus101** [comment]
Issues:

- Do a manual import with a .mkv .en.srt .nl.srt file. Imports the .mkv and a single .srt without suffix. (Both files should be imported with the proper language)
- got to the series folder, rename the .mkv file by adding something like a character in the episode title. hit refresh series. srt file gets deleted/recycled. (File shouldn't be deleted, ideally this would get linked to the file still and renamed? though this is a bit outside the scope of Sonarr, IMO)
- Rename Preview doesn't show extra files (I don't think this is critical, but would be great to have).

**Comment by markus101** [comment]
Rebased and fixed the importing not using the proper language as part of the extension.

**Comment by Taloth** [comment]
Won't that change the extension column in the db?

**Comment by markus101** [comment]
Looks like past me thought of that and we get it from the path again before returning the `TExtraFile`.

**Comment by Taloth** [comment]
Not entirely: https://github.com/Sonarr/Sonarr/pull/1544/files#diff-1778dc79c400fb3c577b08af93f8c40fR61

Don't redefine 'extension', for all ExtraFiles the extension is the same thing, the file extension. Don't concat the language there.

What you need to do is add a function that Builds the new filename in it's entirety, including extension. Not a 'GetExtensionWithSuffix'.
That might also help deal with the code duplication between the MoveFilesAfterRename methods.

**Comment by markus101** [comment]
I'm referring to: https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/Extras/Files/ExtraFileManager.cs#L64 which is getting the extension from the file.

We can get the new file name separately and pass that in instead of building it there and DRY things up a bit though...

**Comment by markus101** [comment]
DRYed out `MoveFilesAfterRename`, but mostly left MetadataService's as-is and can revisit cleaning it up another time as it will be more invasive.

**Comment by nzbjamz** [comment]
Awesome work @markus101! 👏

**Comment by zjpleau** [comment]
How do you enable this feature?

**Comment by markus101** [comment]
Media Management: Import Extra Files and set the extensions to import. It's an advanced setting. It's not released in a master release yet, just develop.

**Comment by dbancajas** [comment]
@markus101  
Do you know when it's scheduled to be merged with the master? Also, how do I use develop branch on-the-fly?

**Comment by spacecabbie** [comment]
hey i am running 0.2.0.654 - Apr 18 2017
I do not see this option ?

**Comment by Taloth** [comment]
@spacecabbie That's a [Radarr](https://github.com/Radarr/Radarr) version number, this is Sonarr.

**Comment by spacecabbie** [comment]
@Taloth Yes i already figured out the diferance :) i have posted in the related treath

**Pull request merged**
