### PR TITLE
Update API docs page to clarify v3/v4 independence

### PR DESCRIPTION
**Pull request by stevietv**
#### Database Migration
NO

#### Description
Expand the description on the swagger UI page to state that the API docs are for API v3 for the v4 frontend

### CODE REVIEW

**Comment by markus101** [comment]
I don't think this makes sense to add, the API version is the same, the fact that v4 has better handling for an enum value for the history event type doesn't invalidate the docs.

**Comment by stevietv** [comment]
> I don't think this makes sense to add, the API version is the same, the fact that v4 has better handling for an enum value for the history event type doesn't invalidate the docs.

What about then a simple statement - 'the v3 API docs apply to both v3 and v4 versions of sonarr. Some functionality may only be available in v4 of Sonarr app'

**Comment by markus101** [comment]
Yeah, I think that a lot better

**Comment by stevietv** [comment]
Done :)

**Review by markus101 — APPROVED** [review]

**Pull request merged**
