### PR TITLE
Add movies support.

### PR DESCRIPTION
**Pull request by vawen**
This PR is not intended to be merged, but to share some ongoing work for #298.
This branch has functional movie support, parse is very simple and uses same qualities as Series.
Search and RSS supports is working, only KAT and RARBG indexers have the searchs implemented for movies.

TODO: MoviesEditor (bulk), Wanted tab (Movies), TestCases (a lot of them!), Decisions (some decisions are common and those ones are in use).

Things I don't like how are done:
- History, Blacklist, PendingRelease: I don't know if it would be better to have separate classes for Movies and Series.
- RSS: At this moment they are together, so you just get 1 RSS from the indexer and then try to parse as series and as movies. I don't know if separate it would be better.
- Manual import is disabled.

### CODE REVIEW

**Comment by pmwoodward3** [comment]
Really excited to see this, if there's anything I can do to help just walk me through it.

**Comment by onedr0p** [comment]
+1 Sonarr handling TV is really stable, would like Movie support.

**Comment by feld** [comment]
+1 as well, this would be a fantastic addition

**Comment by Beatusvir** [comment]
+1 !! nice nice

**Pull request closed without merging**
