### PR TITLE
Feature/transmission seeding

### PR DESCRIPTION
**Pull request by beschoenen**
#### Database Migration
NO

#### Description
This PR adds the ability to set a custom seed ratio and seed idle time for transmission.

#### Todos
- [ ] Tests ?

### CODE REVIEW

**Comment by markus101** [comment]
Seeding ratios need to be configured per indexer, not per download client and as long as Sonarr can get the seeding time/ratio from the download client nothing needs to be set on each torrent. Sonarr would make a decision when processing to determine if it already met the seeding goals and then remove the item from the download client.

**Comment by beschoenen** [comment]
Ok, I'm almost done with your way of implementing this feature, but could you tell me how I would get the indexer used to download a `TrackedDownload`. I'm trying to implement it [here](https://github.com/Sonarr/Sonarr/blob/develop/src/NzbDrone.Core/Download/TrackedDownloads/DownloadMonitoringService.cs#L116)

**Comment by markus101** [comment]
You'd have to get the indexer from the `grabbed` history event using the `DownloadId` (torrent hash in this case).

**Comment by beschoenen** [comment]
Continued in #2272

**Pull request closed without merging**
