### PR TITLE
New: Date format in log files

### PR DESCRIPTION
**Pull request by bakerboy448**
#### Database Migration
NO

#### Description
A few sentences describing the overall goals of the pull request's commits.

#### Issues Fixed or Closed by this PR

*

### CODE REVIEW

**Comment by markus101** [comment]
> A few sentences describing the overall goals of the pull request's commits.

Did not follow template, unclear why we should merge this. Serious question though, why?

**Comment by bakerboy448** [comment]
Follow ISO 8601 date format as a best practice

Also current status is suboptimal as the log cannot be successfully parsed by Third parties.

`20-4-21 or 22-4-21`

**Comment by markus101** [comment]
If you have logs for over a year are you even using Sonarr?

**Comment by markus101** [comment]
If we're going for ISO 8601 (which I'm in favour of) we should update it to `yyyy-MM-dd`

**Comment by bakerboy448** [comment]
Fair lo

**Pull request merged**
