### PR TITLE
Fixed: Prevent grabbing if episode hasn't aired

### PR DESCRIPTION
**Pull request by vawen**
Issue #969

### CODE REVIEW

**Comment by thezoggy** [comment]
does this allow to be series specific (using tags? edit show / can be bulk set in series editor)

**Comment by vawen** [comment]
At this moment it is a global setting. It can be changed easily to be defined per indexer,
I would need to check about tags (have not played with it).

**Comment by markus101** [comment]
I don't think per series makes a lot of sense (support hell). Torn on per indexer, most indexers that actually have this problem also support verified only releases which avoids this issue at the cost of missing out of some less common series.

**Comment by thezoggy** [comment]
the only time ive ever seen this feature to be a benefit is due to spammers trying to post fake GoT
lots of shows have ep released early.. which is why id want to not turn it on globally but only for a very specific show...
if i was to use it (i wouldnt, unless the need arises) 

ideally people should just use better indexers... but what if its an indexer thats normally good.. 
and the admin/mods are just away.. hence the GoT spam that happend each week for a month straight

globally setting it on, i'd think would do more harm than good.. as lots of people may be mift at the fact that the release they want is now too old to grab because of this cock blocking it
example, first ep of supergirl came out 6months early
thus if you waited for it to 'air' then well.. your going to try and grab an ep 6 months old

if you offer the series wide on/off.. you really should extend that to series specific/tags
and its no more 'support hell' than require/ignore words

**Comment by Serneum** [comment]
Some more examples of where this might not be a good idea globally:
1. The Magicians. The first episode aired early but the official premiere is a two-parter this week.
2. The Shannara Chronicles. The first four episodes were made available online and then also aired weekly. 
3. DaVinci's Demons. The entire 3rd season was put online and then one episode was aired per week for 10 weeks.

That being said, I like the idea. I'd probably leave it off unless a series was having some issues. It might help with Saturday Night Live where sometimes the promos for the episodes get grabbed instead of the actual episodes.

**Comment by markus101** [comment]
Good point about tags, I'd be for a tag based approach with the ability to apply all series by leaving it untagged. One option to enable and another to set the tags.

**Comment by vawen** [comment]
Sound good, will implement the tag approach.

**Comment by markus101** [comment]
@vawen sorry, I didn't mean to say get started immediately, I was hoping to get @Taloth or @kayone to weigh in first as it really changes the behaviour of the feature and may impact other decisions we make about settings.

**Comment by Taloth** [comment]
We would be moving from an initial "no, too many good releases get released early, fix your indexer, and remove TPB" stance to "yeah, sure, we'll make it fully customizable".
If we do something like this we might as well make most configuration options 'tagable'. (mind you, that was one of the original concepts from when we started with tags, but considered too complex)
So, no, I can't agree with this.

Personally I would say: Keep just one global flag. If we ever decide to embrace tags, we can always add it. But for now, if ppl want to take the shortcut and turn the flag on, they can. Yes, they might have issues with episodes that are always released early, bad luck, it's them with crappy indexers, not us.
(btw. Looking at the code there's still some remnants from a per-indexer option, which should be removed)

But really, what are we trying to solve here? The question isn't about 'early' releases, it's about early releases occasionally being fake.
Why not add a config option that delays anything released before airdate until x hours after airdate? Preferring those released after?
With usenet you get the chance that the download is no longer available, but that's the tradeoff, it's a bit more softlogic compared to a hard rejection.
Easily done with ```public RejectionType Type { get { return RejectionType.Temporary; } }```

But why stop there? you can add the config option to Delay Profile, after all, 'delaying' is what we're talking about now. (You'll even get your tags for free... dammit why did I suggest this?!)

Only issue is how to reliably reduce the priority of such releases, without risking valid early 1080p releases from losing to some later SD release.

Anyway, think about it.

Sry, for the wall of text.

**Comment by vawen** [comment]
If you really think about the problem it is crap indexers allowing fake uploads so it would have sense to have this linked per indexer. Just my 2 cents. (I had this problem only 1 time with kat)

**Comment by markus101** [comment]
@vawen thats definitely a big source of it, but in a lot of cases the users are using only crappy indexers, blocking at purely at the indexer level still doesn't solve things that legitimately come out before the release date (airs a day earlier in another country) and blocking it per series would help there.

**Comment by vawen** [comment]
Hum, maybe per indexer and be able to disable on individual shows? Probably it is too complex, for that route I think it would have more sense a tag approach.

**Comment by markus101** [comment]
I think for now lets do it with tags.

**Comment by markus101** [comment]
To clarify, I was referring to a delay profile with tags, which has its own complexities and a lot of logic that needs to support that (the more I think about it the more complicated it gets).

I think we're starting to over think this and trying to solve a bunch of potential uses when really we've been asked for a super simple toggle and we're getting away from that. A small percentage of the total user base has asked for this, so lets not over think this and go with a simple toggle, which applies to all indexers and all series.

**Comment by wejendorp** [comment]
What prevents this from getting merged?

**Pull request closed without merging**
