### PR TITLE
LanguageParser: Support both 'ger' and 'ger dub' in language regex

### PR DESCRIPTION
**Pull request by NextWork123**
#### Description
Hello, I have noticed that the current regex handling for the German language is a bit restrictive. Previously, we could only use "GER" when accompanied by dubbing. However, to improve flexibility, I propose modifying the regex so that "GER" can be used both with and without dubbing.

This adjustment would ensure consistency and better alignment with the original project goals.

Please let me know if this update is feasible or if further clarification is required.

Best regards,
NextWorks

### CODE REVIEW

**Comment by thezoggy** [comment]
it was done to prevent false positives..

**Comment by NextWork123** [comment]
> it was done to prevent false positives..

To make Sonarr recognize GER, do I need to create a custom format? 

{55367738-D317-45B2-AF3B-865EC2D927EF}

**Comment by markus101** [comment]
Each of those releases has audio tracks for each of those listed languages? Or are they subtitle languages?

If it's the former, then tests need to be added to validate these changes.
If it's the latter, then _not_ matching is intentional, languages are audio languages, not subtitle languages.

**Comment by NextWork123** [comment]
> Each of those releases has audio tracks for each of those listed languages? Or are they subtitle languages?
> 
> If it's the former, then tests need to be added to validate these changes. If it's the latter, then _not_ matching is intentional, languages are audio languages, not subtitle languages.

How should we handle the situation when both the audio and subtitle languages are in GER?

**Comment by markus101** [comment]
Subtitle languages aren't a concern for Sonarr, they're not tracked.

**Comment by NextWork123** [comment]
> Subtitle languages aren't a concern for Sonarr, they're not tracked.

Got it, thank you for your time! 👍

**Pull request closed without merging**
