### PR TITLE
Fixed: Remove dead Torznab presets

### PR DESCRIPTION
**Pull request by ilike2burnthing**
#### Database Migration
NO

#### Description
Remove dead Torznab presets - HD4Free.xyz and Nyaa Pantsu.

Again, tidy/change whatever.

#### Todos
- [x] Tests
- [ ] Wiki Updates

#### Issues Fixed or Closed by this PR

*

### CODE REVIEW

**Comment by stevietv** [comment]
Thanks for this. This one fails to build right now until the `using System.Linq;` is removed from `TorznabSettings.cs` - its no longer used anymore.

**Review by stevietv — CHANGES_REQUESTED** [review]
update using directives
Thanks for this. This one fails to build right now until the `using System.Linq;` is removed from `TorznabSettings.cs` - its no longer used anymore.

**Review by stevietv — APPROVED** [review]
I was just about to comment my review when I saw a new commit:

> The intention of validation of an having an API was because we knew that these specific indexer templates required an API key. By removing the && check against the whitelist we are now requiring every Torznab implemented indexer to have an API key, which may not be correct.
> I see two options here:
> 
> 1. Keep the ApiKeyWhiteList string array, only empty, and keep the validation against it, just incase a new template torznab is added in the future where we know an ApiKey is required. This may be an inefficient check, though minimal.
> 2. remove the validation rule ` RuleFor(c => c.ApiKey).NotEmpty().When(ShouldHaveApiKey);` and the function `ShouldHaveApiKey`

Seems you also caught that and went for option 1 :D

**Comment by ilike2burnthing** [comment]
I swear that check was fine a minute ago :/

`using System;` missing?

**Comment by stevietv** [comment]
> `using System;` missing?

correct, your using now Array.Empty :)

Build checks take a little while to run.

**Review by markus101 — APPROVED** [review]

**Pull request merged**
