### PR TITLE
Fixed: Enable parsing of repacks with revision

### LINKED ISSUE #5383: REPACK2 in filename fails to be parsed as revision
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Example 1: `REPACK` *does* get parsed as a repack and revision
```json
{
  "title": "My.Hero.Academia.S06E13.REPACK.CR.WEB-DL.1080p.AAC2.0.H.264-Vanilla.mkv",
  "parsedEpisodeInfo": {
    "releaseTitle": "My.Hero.Academia.S06E13.REPACK.CR.WEB-DL.1080p.AAC2.0.H.264-Vanilla",
    "seriesTitle": "My Hero Academia",
    "seriesTitleInfo": {
      "title": "My Hero Academia",
      "titleWithoutYear": "My Hero Academia",
      "year": 0
    },
    "quality": {
      "quality": {
        "id": 3,
        "name": "WEBDL-1080p",
        "source": "web",
        "resolution": 1080
      },
      "revision": {
        "version": 2,
        "real": 0,
        "isRepack": true
      }
```
Example 2: `REPACK2` *does not* get parsed as a repack and revision
```json
{
  "title": "My.Hero.Academia.S06E13.REPACK2.CR.WEB-DL.1080p.AAC2.0.H.264-Vanilla.mkv",
  "parsedEpisodeInfo": {
    "releaseTitle": "My.Hero.Academia.S06E13.REPACK2.CR.WEB-DL.1080p.AAC2.0.H.264-Vanilla",
    "seriesTitle": "My Hero Academia",
    "seriesTitleInfo": {
      "title": "My Hero Academia",
      "titleWithoutYear": "My Hero Academia",
      "year": 0
    },
    "quality": {
      "quality": {
        "id": 3,
        "name": "WEBDL-1080p",
        "source": "web",
        "resolution": 1080
      },
      "revision": {
        "version": 1,
        "real": 0,
        "isRepack": false
      }
```

### Expected Behavior

REPACK2 gets parsed as a repack and the next revision over REPACK.

```json
{
  "title": "My.Hero.Academia.S06E13.REPACK2.CR.WEB-DL.1080p.AAC2.0.H.264-Vanilla.mkv",
  "parsedEpisodeInfo": {
    "releaseTitle": "My.Hero.Academia.S06E13.REPACK2.CR.WEB-DL.1080p.AAC2.0.H.264-Vanilla",
    "seriesTitle": "My Hero Academia",
    "seriesTitleInfo": {
      "title": "My Hero Academia",
      "titleWithoutYear": "My Hero Academia",
      "year": 0
    },
    "quality": {
      "quality": {
        "id": 3,
        "name": "WEBDL-1080p",
        "source": "web",
        "resolution": 1080
      },
      "revision": {
        "version": 3,
        "real": 0,
        "isRepack": true
      }
```

### Steps To Reproduce

1. Import/Parse any release that has been repacked more than once.

### Environment

```markdown
- OS: Ubuntu 20.04
- Sonarr: 4.0.0.357
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome
```

### What branch are you running?

Develop

### Trace Logs?

https://privatebin.net/?5903e8ea156b2c44#4yJZMa5wzzKm9RDqBUJSKhkW7sh1dwrAScYrzwcsr54d

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by stevietv**
#### Database Migration
NO

#### Description

release names containing REPACK2 (etc) don't get parsed as a repack

#### Issues Fixed or Closed by this PR

* fixes #5383

### CODE REVIEW

**Comment by Qstick** [comment]
Should we also set the quality version based on this so that a REPACK gets upgraded to a REPACK2, etc?

**Comment by stevietv** [comment]
> Should we also set the quality version based on this so that a REPACK gets upgraded to a REPACK2, etc?

I'm not sure on this one - I suppose it could be built into the version regex, but then in this case a REPACK2 = version 3 etc so that might not be the cleanest. Wonder if its necessary for how infrequently it might occur :)

**Comment by Qstick** [comment]
Yea, peeking our release stats, looks like REPACK2 comes up a good bit, but anything higher than that is almost non-existent.

**Comment by stevietv** [comment]
> Yea, peeking our release stats, looks like REPACK2 comes up a good bit, but anything higher than that is almost non-existent.

This should be captured now. repackX or reripX gets version X+ 1

**Comment by stevietv** [comment]
hmm, broke a couple of 'REAL' tests by in `ExtendedQualityParserRegex` returning early. gotta switch that return up

**Comment by stevietv** [comment]
> hmm, broke a couple of 'REAL' tests by in `ExtendedQualityParserRegex` returning early. gotta switch that return up

this is fixed now, all parser tests pass

**Pull request merged**
