### PR TITLE
Fanzub url can now be modified [migration 82]

### PR DESCRIPTION
**Pull request by Taloth**
Running a bit ahead to the possibility that ppl will use the fanzub sources to setup alternative sites. This allows em to configure the url for Sonarr.

### CODE REVIEW

**Comment by kayone** [comment]
I think we should hold this off until it happens.

**Comment by Taloth** [comment]
I've seen a couple of ppl working on it, not sure if they're going to be successful. But wouldn't it be nice to be a bit ahead?
But yes, PRed it just to be ready, and to reserve the migration ID.

**Comment by markus101** [comment]
Whats the drop dead date? 31st of March?

I think this is likely the direction it will go, my only concern is there will be a bunch of them that don't work 100% correctly and it ends up being a pain to support, but thats not a big concern for me.

**Comment by kayone** [comment]
are there any indication that someone might be launching one of these?

**Comment by markus101** [comment]
Looks like this might be a clone: http://www.animenzb.com/

**Pull request merged**
