### PR TITLE
Fixed: sorting for series "A.P. Bio"

### PR DESCRIPTION
**Pull request by Thirrian**
https://forums.sonarr.tv/t/a-p-bio-sorting-under-p/17959

- Added sorting for "A.P. Bio"
- Added unit test
- Removed name normalization for series which was deleted on thetvdb

### CODE REVIEW

**Comment by Taloth** [comment]
Can you add em to the unit tests too?

**Comment by Thirrian** [comment]
I've added the test, and found a series that no longer exists so I removed it. Technically that is a separate issue, but given the size of the change I hope it's ok to include it here as well.

**Comment by Taloth** [comment]
that's fine.

**Comment by nova-techies** [comment]
Dunno if this is the right place for this but the forums led me here.

I just updated to 2.0.0.5163 and I'm still having A.P. Bio sorting under 'P' and not 'A'.  Did I miss a step here?

**Pull request merged**
