### PR TITLE
fixed moment.js deprecated zone

### PR DESCRIPTION
**Pull request by Fish2**
#### Database Migration
NO

#### Description
fixed moment.js deprecated zone and add

don't pull in yet got issues 

#### Todos
- [ ] Tests
- [ ] Documentation

#### Issues Fixed or Closed by this PR

* https://github.com/Radarr/Radarr/issues/2231

### CODE REVIEW

**Comment by markus101** [comment]
Why the two unrelated commits?
As mentioned previously images have already been compressed and aren't used by the UI https://github.com/Sonarr/Sonarr/pull/1959

**Comment by Fish2** [comment]
I can remove them but why not Compression them fully its lossless so makes no difference

**Comment by markus101** [comment]
They're unrelated to this PR, so shouldn't be included here. As for why not, there is little value in compressing the same thing multiple times, another pass of pingo would also remove some size, but not something we think is worthwhile.

**Comment by Fish2** [comment]
Ok i have removed the other 2 commits. Yer true

**Pull request closed without merging**
