### PR TITLE
Added support for 2160p releases

### LINKED ISSUE #876: 4k Quality Definitions
4k is coming/already here so we should add the applicable quality settings, possible rejig the default ordering as well, is source or resolution more important?

### PR DESCRIPTION
**Pull request by Dahlgren**
Fixes #876

### CODE REVIEW

**Comment by markus101** [comment]
I think it makes sense to add support for HDTV and Bluray 2160p releases as well as a new default HD 2160p profile to match the 720p and 1080p default profiles.

**Comment by Dahlgren** [comment]
Alright, I'll add 2160p HDTV and 2160p Bluray

**Comment by Dahlgren** [comment]
HDTV2160p and Bluray 2160p added. I couldn't find any releases for those formats yet so no parser tests have been added for them.

**Comment by Taloth** [comment]
Markus, doesn't seem to be a good idea to add more qualities like this. Becomes too much.
We should do this only in conjunction with the webrip and grouping/simplification ideas that were discussed.

**Comment by thezoggy** [comment]
ideally right now there is only 2 forms of 4k content. web and bluray (coming soon) . broadcast 4k just doesnt happen (unless for special ces event.. but still it'd be so heavily compressed no one would prob really want it... so not worth the noise).

**Comment by Dahlgren** [comment]
Should I remove HDTV 2160p and keep WEB-DL 2160p plus BluRay 2160p then?

**Comment by JigSawFr** [comment]
Many 2160P releases are coming, they are detected as 480P releases.
For example:
```
Marvels.Jessica.Jones.S01.2160p.NF.WEBRip.DD5.1.x264-iON
Marvels.Jessica.Jones.S01.2160p.NF.WEBRip.DD5.1.x264-TrollUHD
```

**Comment by markus101** [comment]
Merged in.

**Comment by markus101** [comment]
And thanks @Dahlgren we had a few discussions about it and @Taloth finalized it.

**Comment by Taloth** [comment]
His commit and f25f5abced09748dada3fb5173db1b74967117fe to finalize. Didn't include the WEBRip stuff I wanted, but at least prepared it and reserved the quality ids.

**Comment by Dahlgren** [comment]
Great!

**Pull request closed without merging**
