### PR TITLE
DownloadStation: Wrong status in enum

### PR DESCRIPTION
**Pull request by margaale**
#### Database Migration
NO

#### Description
Adding captcha_needed status as it wasn't listed in the docs. Changed the other two statuses to fix their names.

#### Issues Fixed or Closed by this PR

*  #2325

### CODE REVIEW

**Comment by Taloth** [comment]
I actually was planning to do a JsonEnumConverter that properly converts the strings. Since download station uses a lowercase format with underscores, should be easy enough to do based on the Upper CamelCase enum values.

**Comment by margaale** [comment]
Something like this? I never did it before...
I couldn't run the test thou, i'm at work now

**Comment by Taloth** [comment]
Something like that yes, although I'll make it a bit more generic so it'll actually work on all enums instead for just that one.

**Comment by Taloth** [comment]
Merged via https://github.com/Sonarr/Sonarr/commit/747f3e171c752a18148c1d115679ba2b9710d260

**Pull request closed without merging**
