### PR TITLE
New: Validate NZBs before sending to download client

### PR DESCRIPTION
**Pull request by markus101**
#### Database Migration
NO

#### Description
Validates NZBs before sending them to the download client.

#### Issues Fixed or Closed by this PR

* #263

### CODE REVIEW

**Comment by Safihre** [comment]
@markus101 Great to find this PR, just some feedback:
`should_throw_when_no_group_in_groups`, is not a nessecary reason to dismiss an NZB, no newsserver nowadays uses groups anymore, only article-ID's.
`should_throw_when_no_segment_in_segments` also not a reason to reject an NZB, SAB and NZBGet just ignore the file.

**Comment by markus101** [comment]
Thanks @Safihre I dropped the following 4 checks:

- `should_throw_when_no_groups_in_file`
- `should_throw_when_no_group_in_groups`
- `should_throw_when_no_segments_in_file`
- `should_throw_when_no_segment_in_segments`

I assumed `groups` and `segments` don't need to be children of `file` if SAB and NZBGet don't care about their being groups or segments within.

**Comment by Safihre** [comment]
Looks good! 
One can always think of more ways in which the NZB could be invalid, but these basic checks will effectively catch 99% of it :+1:

**Comment by Safihre** [comment]
I couldn't make it up from the code, but what happens if the NZB is invalid? Is the whole indexer ignored in general or just the 1 specific NZB or release?

**Comment by markus101** [comment]
That particular NZB is ignored and if available, another will be tried (could be the same release from another indexer or a different one altogether). I suppose we could also look at using invalid NZBs from an indexer as a sign that the indexer should be ignored for a period of time.

**Comment by Safihre** [comment]
Yes, I would definitely think so. Maybe a minimal delay, but at least that it's not hit again in the same fetch/RSS session.

**Comment by Safihre** [comment]
@markus101 lets get it in? In its current form it's already a great addition :)

**Comment by markus101** [comment]
Thanks for the reminder @Safihre, merged.

**Pull request merged**
