### PR TITLE
Fixed: Paths with colons prevent Sonarr from communicating with Transmission

### PR DESCRIPTION
**Pull request by vawen**
Issue #954

### CODE REVIEW

**Comment by markus101** [comment]
I'm not seeing how this solves the issue, OsPath would still throw in that case.

**Comment by vawen** [comment]
This problem only appear when a magnet is added and is downloading the metadata. Once the metadata is downloaded, the name of the torrent change and removes forbidden characters.

**Comment by markus101** [comment]
The path is the issue, not the name, the forum post linked in #954 shows the full path Sonarr had issues with.

**Comment by Taloth** [comment]
Yes, but the name isn't a path, it's the display name provided by the magnet url. Once the magnet finishes downloading and the torrent becomes available, the release name of either the dir or file is used instead.
I still agree we ought to fix the colon, but that's just a contributing factor, not the original issue. (I intended to fix the colon when merging in this PR, so don't worry about it :D)

**Pull request merged**
