### PR TITLE
Add Tags to existing Series from multiple Import Lists

### PR DESCRIPTION
**Pull request by danimart1991**
#### Database Migration
NO

#### Description

Add Tags to existing Series if available in multiple Import Lists.

#### Todos
- [ ] Tests
- [ ] Wiki Updates

### CODE REVIEW

**Comment by bakerboy448** [comment]
Movie? 👀 😉

**Comment by danimart1991** [comment]
> Movie? 👀 😉

Fixed. 😅 Thanks for review.

**Comment by markus101** [comment]
We’ve discussed an this isn’t something we are going to support. Tags will be added when Sonarr adds the series, otherwise they will not be tagged. This allows people to tag the series with a unique tag for the list and not have it alter tags on existing series.

**Comment by danimart1991** [comment]
> We’ve discussed an this isn’t something we are going to support. Tags will be added when Sonarr adds the series, otherwise they will not be tagged. This allows people to tag the series with a unique tag for the list and not have it alter tags on existing series.

I think this problem could be fixed if the "add multiple tags" is an option, but ok... Thanks for review it. 😉

**Pull request closed without merging**
