### PR TITLE
New: Use absolute timestamps for series and episode history

### PR DESCRIPTION
**Pull request by mynameisbogdan**
#### Description
Switching to absolute dates to make it easier to debug upgrades for users. Bonus making the series history modal wider.

#### Screenshots for UI Changes
image

### CODE REVIEW

**Comment by markus101** [comment]
Relative dates have an option to disable already, we could change the default for that to not be enabled, but I don't think we should remove relative dates from these history items completely.

**Comment by stevietv** [comment]
From a support point of view I am enthusiastic about this change. Will help when discussing screenshots

**Comment by markus101** [comment]
Adding an option to make relative date cells include a time stamp should cover it and another for second accuracy, to include seconds since that's missing today. Relative with timestamp it could be something like `{relativeDate} at {timestamp}` (which will be today/yesterday as long as people have their dates set correctly) to be properly translated, if it's something not rendered as a relative date use the short date format + timestamp.

This way we don't introduce a breaking change because relative dates are stripped out completely and we can still improve the support experience.

**Comment by markus101** [comment]
Closing in favour of https://github.com/Sonarr/Sonarr/pull/6811

**Pull request closed without merging**
