### PR TITLE
New: Discord notification upgrade colour

### PR DESCRIPTION
**Pull request by RobinDadswell**
#### Database Migration
NO

#### Description
Made the upgrade notification colour to be more clear than the grey that blends in with Discord's background

#### Todos
- [ ] Tests
- [ ] Documentation

#### Issues Fixed or Closed by this PR

* #4044

### CODE REVIEW

**Comment by markus101** [comment]
Purple is "downloading" for everything else in Sonarr, it doesn't make sense to use that here, another shade of green would make the most sense.

**Comment by RobinDadswell** [comment]
alright, I will do that now.

**Comment by RobinDadswell** [comment]
https://www.htmlcsscolor.com/hex/003520 I have used that colour

**Comment by Taloth** [comment]
Can you post a screenshot?

**Comment by RobinDadswell** [comment]
@Taloth here is an image of the green
image

**Pull request merged**
