### PR TITLE
Update RemotePathMappingEditViewTemplate.hbs

### PR DESCRIPTION
**Pull request by DaveIsMe**
You need the IP of the Host and it seemed like you needed the name of the host with the original wording so I've suggested the world's smallest change.

### CODE REVIEW

**Comment by Taloth** [comment]
Actually, no, you need to fill in the value used in the Host field when configuring the Download Client in Sonarr. which could be IP or dns name.

**Comment by DaveIsMe** [comment]
Oh, my bad, I read it as wanting the name of the host you gave but I see what you mean now.

**Comment by Taloth** [comment]
It does mean it could use better clarification.

**Comment by DaveIsMe** [comment]
Yeah possibly. I was thinking could you have a dropdown box with the various options rather than having users type it themselves, which is prone to misunderstanding and typos. If I can teach myself some of this Handlebars.js stuff, I'll see if I can submit a better patch.

**Pull request closed without merging**
