### PR TITLE
New: Support for Postgres database

### PR DESCRIPTION
**Pull request by 3744111**
#### Database Migration
YES | NO

#### Description
Starts of Postgres support for Sonarr using Prowlarr/Radarr commits as a base:

https://github.com/Prowlarr/Prowlarr/pull/515
https://github.com/Prowlarr/Prowlarr/pull/633
https://github.com/Prowlarr/Prowlarr/pull/865
https://github.com/Radarr/Radarr/pull/6873

#### Todos
- [ ] Tests
- [ ] Wiki Updates

#### Issues Fixed or Closed by this PR
#4175 
#1669
#4373
#3764

### CODE REVIEW

**Comment by bakerboy448** [comment]
You'll probably wanna swing by discord and chat this one out before spending too much more time and effort on it.   Previously Markus and taloth have indicated they have no plans whatsoever to support any other database besides SQLite.

**Comment by 3744111** [comment]
Alright, I'll swing by discord and see if we can figure something out. I did see that there are no plans for supporting other databases due to differences between version, but having implemented Postgres it really not that bad. There are about 3 places where the queries are different between SQLite and Postgres.

**Comment by teambvd** [comment]
Would be grateful to see this implemented. I've gotten around some of the growing performance issues I've had with Sonarr over the last 4-6 months (15+ seconds to view download history, and again each time paging through, among others) or so by tuning the SQLite DB a bit. Maxing out the page size (along with a vacuum to take effect - vacuum alone made no noticeable impact), and matching that to the block size on the storage side brought it back down to ~3-ish seconds, much closer to 'normal'. But I fear even that might just be a bit of a band-aid.

I don't really need anything more than SQLite for Radarr, as even 10k items should be fine (was with Sonarr anyway). But for Sonarr (and probably Lidarr as well, but that's a different matter), it seems about the time I ticked over ~23-25k items, it started getting pretty sluggish even on it's mirrored NVME pool.

**Comment by anthr76** [comment]
Any chance of seeing this merged anytime soon?

**Comment by nwilging** [comment]
+1 to this. Recently integrated postgres with radarr and the performance boost is like a night and day difference. I am bound to using network shares for my servarr volume mounts, and so I encounter _frequent_ issues with sqlite.

With the growing popularity of containerization and cloud-based deployments, it would be great to see database support in Sonarr that isn't limited by network-mounted storage devices.

**Comment by arestifo** [comment]
Any updates on this?

**Comment by feld** [comment]
I've been using Radarr with Postgres and it has been noticeably faster. I hope to see Postgres support make its way into Sonarr too...

**Comment by wsidl** [comment]
Seeing comments like this from @bakerboy448 on #4175:

> We don't have plans to support another DB engine at this time, it's a significant change that would require validating all migrations on every DB engine supported (adding MySQL would only open the doors to add more) and deal with differences in various versions (which we've run into with SQLite a few times).

Maybe this is my lack of familiarity with .Net, but I know in any other language, using any decent ORM with a database migration plan would resolve all of this. I deal with multiple database types on a regular basis and only use SQLite for local development specifically for all the reasons people mention above: it's faster, it's fault tolerant, it's naturally backed up.

It's for this very reason I'd be happy to find another platform to support my needs.

**Comment by bakerboy448** [comment]
@wsidl postgres is on the table;  nothing beyond that for the Starrs

the Radarr comments markus noted have been resolved.  But as you can see from OPs attempt here and from the other Starr postgres migrations - it's a lot of effort rewriting effectively every migration and db query to be postgres compliant / conditionalized for postgres if needed.

**Comment by wsidl** [comment]
Thanks @bakerboy448, but my point is there are tools and libraries (ORMs) that handle the database types for you. Quick search through the code base and looks like the project's using Fluent Migrator and Dapper, both of which all support all database types users in your previous issues have been requesting.

Knowing this now and my lack (and un-willingness to touch .Net), why can't we use these libraries to their full extent?

**Comment by markus101** [comment]
Using an ORM doesn't remove the need to support the underlying DB engine, if we're going to support something then we're going to have an environment to test and debug it in, we're not going to do that for multiple dedicated DB engines.

**Comment by onedr0p** [comment]
I agree with @markus101 ORM doesn't really buy too much here if the primary focus is sqlite with postgresql as an option, in fact it might get in the way more if it's not fully compliant with the needs of Sonarr. Postgres is by far the best RDBMS database option out there and I do not think anything else needs to be supported for an external database here.

**Comment by Qstick** [comment]
Replaced by #5559

**Comment by wsidl** [comment]
Don't know what kind of work is involved to make integration and e2e tests work for this app, but I've typically written automated test strategies to iterate through a series of connection strings to all database types I've wanted to support. This would then be run through a container in a CI pipeline. Since this is an OS project, you can get this functionality for free on most platforms.

From the sounds of it, doing anything in .Net is more complicated than it should be.

**Pull request closed without merging**
