### PR TITLE
Changed exit statement to "Press enter to exit..." to match use of ReadLine()

### PR DESCRIPTION
**Pull request by ashleybroughton**
#### Description
Minor fix to match input request in NzbDrone.Console/ConsoleApp.cs
Changed "Press any key to exit..." prompt to "Press enter to exit..."

### CODE REVIEW

**Comment by Taloth** [comment]
tbh, I would rather have it on Enter. 'Any key' is a bit too easy, for example, pressing the windows key to open a notepad to copy/paste the error in would be enough.

**Comment by markus101** [comment]
I was thinking the same as @Taloth

**Comment by ashleybroughton** [comment]
I have updated the commit to reflect your preferences.

**Comment by thezoggy** [comment]
Maybe Escape is a better choice?

**Pull request merged**
