### PR TITLE
Compiler: Support for XBuild

### PR DESCRIPTION
**Pull request by larsjohnsen**
Continues #202 as it was merged then reverted.

I've fixed the issue that  `[...] the signatures are different` as mentioned by markus101 in https://github.com/Sonarr/Sonarr/pull/202#issuecomment-75893962.

### CODE REVIEW

**Comment by kayone** [comment]
thanks for reopening it.

**Comment by larsjohnsen** [comment]
I'd appreciate getting "Fix case inconsistencies" and "Fix case inconsistencies" merged, as they contain fairly benign changes.

**Comment by markus101** [comment]
Which ones? You referenced the first one twice. Please open a new PR for "Fix case inconsistencies" so we can review before merging.

**Comment by markus101** [comment]
Added changes that allow it to build under mono.

**Pull request closed without merging**
