### PR TITLE
Added: Ntfy provider for notifications

### PR DESCRIPTION
**Pull request by psylenced**
* Added: Ntfy provider for notifications.

* Changed: Clean up of validation and fields for ntfy

* Fixed: Unused title setting, and spelling issue.

(cherry picked from commit dca00db)

#### Database Migration
NO

#### Description
This adds ntfy.sh as a notification provider.

It allows public server or private instance.

Cherry-picked via Radarr.

#### Todos
- [ X ] Tests

### CODE REVIEW

**Comment by markus101** [comment]
Thanks!

**Comment by bakerboy448** [comment]
Closed #5088

**Comment by Iceman248** [comment]
I have Sonarr 3.0.9.1549, but I don't see ntfy. Is it only in a newer version?

**Comment by MathieuMoalic** [comment]
This commit was made on the `develop` branch. You can have this feature if you wait until (if) it gets merged on the main branch or get the develop version of the app ( `ghcr.io/linuxserver/sonarr:develop` for the container image for example ). Alternatively, Custom Scripts work with ntfy.sh on the current version of Sonarr: https://github.com/nickexyz/ntfy-shellscripts

**Comment by Iceman248** [comment]
I did eventually figure that out, thanks.

**Comment by panayotovip** [comment]
it is in dev more that a year.
is there a plan to implement to stable ?

**Pull request merged**
