### PR TITLE
Removed VOSTFR from french parsing

### PR DESCRIPTION
**Pull request by bizen-ya**

### CODE REVIEW

**Comment by markus101** [comment]
If I'm not mistaken, VOSTFR subs are hardcoded (or often are at least), given that, this is expected behavior and removing this would be a step backwards for a large number of users (thousands).

This is something we can look at improving later on, but without a clean migration it will cause too many issues.

**Comment by thezoggy** [comment]
yes, please dont allow VOSTFR.

**Comment by bizen-ya** [comment]
I dont think there is a lot of people who want a mix of french and hardsubbed show... You can reject if you want, i have compiled one version for myself.

**Comment by thezoggy** [comment]
sure, your change completely goes against the purpose of its intended effect. classify non english release as such. feel free to close this.

**Comment by bizen-ya** [comment]
I think that a hard subbed release should be categorized as english, but it's m'y own view... I close the request

**Pull request closed without merging**
