### PR TITLE
Check output path on diskstation settings

### PR DESCRIPTION
**Pull request by margaale**
#### Database Migration
NO

#### Description
Some radarr users have been experiencing some issues regarding permissions and access to the output path, it seems to me that they don't know how to properly setup download station client, so it looks like it's  a good idea to check if the output path exists at the moment of adding this client.

### CODE REVIEW

**Comment by Taloth** [comment]
No need to fix it, but question: What does download station do if a subfolder does not exist, but the shared folder does? Like what happens when you use TvCategory.

**Comment by margaale** [comment]
It returns isDir = false. That's why i wrote that extra check in there. And if the shared folder does not exists it returns additional_info in null.

**Comment by Taloth** [comment]
What I mean, what happens if you actually create the download task?

**Comment by Taloth** [comment]
Why I ask, is because I think we might only need to test this if TvDirectory is set, but not if TvCategory is. If the tvcategory directory is created automatically by downloadstation.

**Comment by margaale** [comment]
Sorry, i thought you were talking about this PR. No, the full path must exists otherwise it returns an error when creating the task.

**Comment by Taloth** [comment]
k, and yes I was talking about the PR-related stuff. I was just cleaning it up, copying it to usenetDLstation etc.

**Comment by Taloth** [comment]
Here https://github.com/Sonarr/Sonarr/commit/3656807522fe2af0a5ee37bbf9c430a184545edf

What do you think?
Obviously I didn't test it.

Significant changes:
- `if (failures.Any()) return;` only needed to abort after connection failures, the other failures can be tested and reported on concurrently.
- Only test directory if either TvDirectory or TvCategory is specified.
- Report the failure for the relevant field with a short message, that way it fits in the UI better.
- Report exceptions globally without explanation, if an exception occurs, it's a failure on our part.

**Comment by margaale** [comment]
Seems ok to me. Gonna test it at home later.

**Comment by Taloth** [comment]
ok lemme know and I'll push to dev tomorrow.

**Comment by Taloth** [comment]
Closed via https://github.com/Sonarr/Sonarr/commit/9304547c957037e505f8eb8b0b92c0e6b4d0b8ec

**Pull request closed without merging**
