### PR TITLE
Set frontend `theme-color` to logo color

### PR DESCRIPTION
**Pull request by agneevX**
#### Database Migration
NO

#### Description
Set `theme-color` to Sonarr's logo color.

09894E05-CCD5-4E5A-9BA2-043A68661B37

#### Todos
- [ ] Tests
- [ ] Wiki Updates

#### Issues Fixed or Closed by this PR

*

### CODE REVIEW

**Comment by thezoggy** [comment]
What about the line below it?

**Comment by Stanzilla** [comment]
Yeah I think it would look better if you'd try to match the header color

**Comment by markus101** [comment]
IIRC the original reason this was changed from matching the header or logo colour was because it was super bright on some devices, not sure if this is something we want to change as it will disrupt existing users.

**Comment by agneevX** [comment]
I see. I've had a chance to review this across devices and I think the current implementation is fine and works well, even with custom CSS themes.

**Pull request closed without merging**
