### PR TITLE
Adds health check failed notification

### PR DESCRIPTION
**Pull request by MitsuhideA**
#### Database Migration
YES - https://github.com/Sonarr/Sonarr/commit/17cfe018a2b05758abf8f700d5d76462d7cc50a6#diff-92efdfbe6bfc71b23ec399a28d1d08e0

#### Description
This feature adds notifications when a health check fails such as a download client going offline.

#### Todos
- [x] Tests
- [ ] Documentation

#### Issues Fixed or Closed by this PR

* #1798

### CODE REVIEW

**Comment by markus101** [comment]
This work needs to be based of off `phantom-develop`, not `develop` As we’re no longer accepting PRs to v2.

**Comment by MitsuhideA** [comment]
Oh alright! I'll get to it.

**Comment by markus101** [comment]
@Qstick implemented this in Lidarr, so it may make sense to cherry pick his work over and fix things on top of it as necessary. https://github.com/lidarr/Lidarr/pull/609 / https://github.com/lidarr/Lidarr/commit/d4d91465997d87296d137f83002de2e405aa0c3a

**Comment by markus101** [comment]
Closing in favour of https://github.com/Sonarr/Sonarr/pull/3253

**Pull request closed without merging**
