### PR TITLE
Sub-titled

### PR DESCRIPTION
**Pull request by GuillaumeLebeau**
Add option to allow subtitled episode or not.
For example if subtitled is not allowed, french episode with "VOSTFR" in file name will not be approved to download, because this is an english episode subtitled in french, not a french audio episode.

### CODE REVIEW

**Comment by markus101** [comment]
First look, the line endings changed so we can't see the actual changes, this will need to be fixed before we can look.

**Comment by markus101** [comment]
Also: https://github.com/Sonarr/Sonarr/pull/692 - we're moving Language to a new profile (we still need to review that PR before we merge it though).

**Comment by GuillaumeLebeau** [comment]
For the problem of line endings I use GitHub Desktop on Windows which use the .gitattributes configuration `*text eol=lf`. How can I fix this?
Do you need some help for the PR https://github.com/Sonarr/Sonarr/pull/692?

**Comment by kayone** [comment]
https://help.github.com/articles/dealing-with-line-endings/

this is what you should do, 

`git config --global core.autocrlf auto`

and re-clone the repo and apply your changes.

**Comment by kayone** [comment]
I'm closing this since it hasn't been updated in 3 months, feel free to open a new PR without the line ending issue

**Pull request closed without merging**
