### PR TITLE
Add disablewal startup arg

### PR DESCRIPTION
**Pull request by onedr0p**
#### Database Migration
NO

#### Description
Add disablewal startup arg (useful for network filesystems) more detail in https://github.com/Sonarr/Sonarr/issues/1886

#### Todos
- [x] Tests
- [ ] Documentation

#### Issues Fixed or Closed by this PR

* https://github.com/Sonarr/Sonarr/issues/1886

I don't know if the PR should be closed if this is merged, however it will make all the people using network file systems happy

### CODE REVIEW

**Comment by Taloth** [comment]
Can you add a IsWalSupported method to ConnectionStringFactory and add the IDiskProvider.GetMount check as suggested in the issue?

If 9P isn't detected properly as network FS then we can deal with that in ProcMountProvider globally. As well as any other edge-case.
I'd love to know what `/proc/mounts` reports for the 9P scenario (and `/proc/filesystems`), it might be handled properly out of the box.

Detecting locking capabilities as Andy suggested is a good idea but more work and doing a network FS check in IsWalSupported should get the ball rolling.

Please note that a docker container on windows _IS_ a HyperV VM. And any disk IO to the Windows host filesystem is using a network filesystem because it communicates via a HyperV vSwitch and not a HyperV attached virtual harddisk. Either CIFS, 9P or NFS or w/e, it's a remote filesystem.   
So detecting that covers most if not all of the cases mentioned in the issue.

**Comment by onedr0p** [comment]
I can try that out, but I also think it would be nice to have the arg just in case it cannot determine the FS type.

**Comment by Taloth** [comment]
If it comes to that then I'd prefer a config.xml option. But let's cross that bridge when we have to, ok?

**Comment by onedr0p** [comment]
Sounds good, I have updated my commits with the network fs detection.

I can also try to add the options to `config.xml` more options the better :)

**Comment by onedr0p** [comment]
Obviously there are some conditional problems in the logic. I would think the command line arg would take precedence. Let me know what you think. Thanks!

**Comment by Taloth** [comment]
Drop the cmdline option in favor of the config.xml option, it's far less code overall since it carries over in restarts automatically. It's also something that's not specific to individual startups so doesn't belong in the cmdline.
Check out ConsoleLogLevel for an example of another 'hidden' config.xml option, maybe DatabaseJournalMode defaulting to 'Auto'. (but I'm telling ya, you won't need it, if the user runs into an old network fs we don't know about _and_ isn't listed in /proc/filesystems, we can throw it in the list)

And might I suggest making GetConnectionString non static. That gives it access to the instance. 
Store _diskProvider like you did earlier, also add IConfigFileProvider, you'll need it later.
Add GetJournalMode(string path) and call it from GetConnectionString.
Check for OsInfo.IsOsx, return Journal.
Check GetMount(path) for network fs, return Journal. (Also maybe log it (fs name and type) at debug level)
else return Wal.
(Somewhere in GetJournalMode you'd also check the config.xml option as provided by IConfigFileProvider.)
That isolates the entire logic in GetJournalMode.

Please lemme know if the logic works properly with the docker setup you had issues with.

**Comment by markus101** [comment]
Users time and time again have proven they toggle things on or off, often forgetting and then wondering why something doesn't work days/weeks/months later.

Less is definitely more with config settings, that's not the power user way, but power users make up a tiny portion of the user base and any setting that has the potential to cause issues we  try to think of better ways to deal with, such as automatic detection and any time we can avoid a user having to make a change (especially an intentionally hidden setting) and have Sonarr just work is a big win. The mere 16 participants in the issue point to this particular issue having a small overall impact to users, albeit a bigger impact to the users that are affected.

I think we should avoid the option until it's absolutely required, but as Taloth said, adding additional drives to be treated as network drives can be done and will improve other aspects of the Sonarr.

**Comment by onedr0p** [comment]
Makes sense to me, I also like the `config.xml` method better because we don't need to modify the `Dockerfile` at all.

I have removed the command line arg and going that way, with the network fs detection.

@Taloth 
> And might I suggest making GetConnectionString non static. That gives it access to the instance.

I have tried this but get a nasty error from TinyIOT, I am not really familiar with what it is complaining about here

```[Fatal] ConsoleApp: EPIC FAIL!

[v10.0.0.33351] TinyIoC.TinyIoCResolutionException: Unable to resolve type: NzbDrone.Core.Datastore.IDbFactory ---> TinyIoC.TinyIoCResolutionException: Unable to resolve type: NzbDrone.Core.Datastore.DbFactory ---> TinyIoC.TinyIoCResolutionException: Unable to resolve type: NzbDrone.Core.Datastore.IConnectionStringFactory ---> TinyIoC.TinyIoCResolutionException: Unable to resolve type: NzbDrone.Core.Datastore.ConnectionStringFactory ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Datastore.ConnectionStringFactory.IsWalSupported(String path) in C:\Users\devin\source\repos\Sonarr\src\NzbDrone.Core\Datastore\ConnectionStringFactory.cs:line 49
   at NzbDrone.Core.Datastore.ConnectionStringFactory.GetConnectionString(String dbPath) in C:\Users\devin\source\repos\Sonarr\src\NzbDrone.Core\Datastore\ConnectionStringFactory.cs:line 74
   at NzbDrone.Core.Datastore.ConnectionStringFactory..ctor(IAppFolderInfo appFolderInfo, IDiskProvider diskProvider, IConfigFileProvider configFileProvider, Logger logger) in C:\Users\devin\source\repos\Sonarr\src\NzbDrone.Core\Datastore\ConnectionStringFactory.cs:line 28
   at lambda_method(Closure , Object[] )
   at TinyIoC.TinyIoCContainer.ConstructType(Type requestedType, Type implementationType, ConstructorInfo constructor, NamedParameterOverloads parameters, ResolveOptions options) in C:\Users\devin\source\repos\Sonarr\src\NzbDrone.Common\TinyIoC.cs:line 3561```

Snippet:

```c#
namespace NzbDrone.Core.Datastore
{
    public interface IConnectionStringFactory
    {
        string MainDbConnectionString { get; }
        string LogDbConnectionString { get; }
        string GetDatabasePath(string connectionString);
        bool IsWalSupported(string path);
    }

    public class ConnectionStringFactory : IConnectionStringFactory
    {
        private readonly IDiskProvider _diskProvider;
        private readonly IConfigFileProvider _configFileProvider;
        private readonly Logger _logger;

        public ConnectionStringFactory(IAppFolderInfo appFolderInfo, IDiskProvider diskProvider, IConfigFileProvider configFileProvider, Logger logger)
        {
            MainDbConnectionString = GetConnectionString(appFolderInfo.GetDatabase());
            LogDbConnectionString = GetConnectionString(appFolderInfo.GetLogDatabase());

            _diskProvider = diskProvider;
            _configFileProvider = configFileProvider;
            _logger = logger;
        }

        public string MainDbConnectionString { get; private set; }
        public string LogDbConnectionString { get; private set; }


        public string GetDatabasePath(string connectionString)
        {
            var connectionBuilder = new SQLiteConnectionStringBuilder(connectionString);

            return connectionBuilder.DataSource;
        }

        public bool IsWalSupported(string path)
        {
            var driveType = _diskProvider.GetMount(path).DriveType;

            if (driveType == DriveType.Network || driveType == DriveType.Unknown)
            {
                return false;
            }

            return false;
        }

        private string GetConnectionString(string dbPath)
        {
            var connectionBuilder = new SQLiteConnectionStringBuilder();

            connectionBuilder.DataSource = dbPath;
            connectionBuilder.CacheSize = (int)-10000;
            connectionBuilder.DateTimeKind = DateTimeKind.Utc;

            if(OsInfo.IsOsx)
            {
                _logger.Debug("Mac OSX operating system detected, disabling WAL mode for SQLite");
                connectionBuilder.JournalMode = SQLiteJournalModeEnum.Truncate;
                connectionBuilder.Add("Full FSync", true);
            }
            else
            {
                if(this.IsWalSupported(dbPath) != true)
                {
                    _logger.Debug("Network filesystem store for application data detected, disabling WAL mode for SQLite");
                    connectionBuilder.JournalMode = SQLiteJournalModeEnum.Truncate;
                    connectionBuilder.Add("Full FSync", true);
                }
                else
                {
                    connectionBuilder.JournalMode = SQLiteJournalModeEnum.Wal;
                }
            }

            if(_configFileProvider.DatabaseJournalMode != "Auto")
            {
                connectionBuilder.JournalMode = SQLiteJournalModeEnum.Truncate;
                connectionBuilder.Add("Full FSync", true);
            }
            else
            {
                connectionBuilder.JournalMode = SQLiteJournalModeEnum.Wal;
            }

            connectionBuilder.Pooling = true;
            connectionBuilder.Version = 3;
           
            return connectionBuilder.ConnectionString;
        }
    }
}```

**Pull request closed without merging**
