### PR TITLE
Added: X265 & TV Documentary categories to NZB Finder

### PR DESCRIPTION
**Pull request by Fossil01**
#### Database Migration
NO

#### Description
Added existing and future X265 and TV Documentary categories to NZB Finder indexer.

#### Issues Fixed or Closed by this PR

* Sonarr not searching in all categories

### CODE REVIEW

**Comment by markus101** [comment]
Why should these be added as defaults as opposed to users adding them if they want them?

x265 is still pretty niche and documentaries are typically named in a way that Sonarr can’t parse them anyways.

**Comment by Fossil01** [comment]
Because there is a ton of stuff out there and users can always block X265 by either removing the category or in their settings.

I'd say that the majority of the users have no clue about adding categories themselves. 

Documentary names:
Hatayasot.2017.DOCU.E02.720p.HDTV.x264-Sweet-Star
Dayan.The.First.Family.DOCU.S01E04.720p.HDTV.x264-HebTV
National.Geographic.Life.On.Mars.WS.PDTV.XviD-hV

**Comment by jalmansor** [comment]
> Because there is a ton of stuff out there and users can always block X265 by either removing the category or in their settings.
> 
> I'd say that the majority of the users have no clue about adding categories themselves.
> 
> Documentary names:
> Hatayasot.2017.DOCU.E02.720p.HDTV.x264-Sweet-Star
> Dayan.The.First.Family.DOCU.S01E04.720p.HDTV.x264-HebTV
> National.Geographic.Life.On.Mars.WS.PDTV.XviD-hV

I agree with @Fossil01 on this, as I've also seen where categories aren't necessarily perfect. Plus, x265 seems to have improved significantly in its support and should be worth adding.

Though, for the sake of argument, could a better solution for documentaries be a new series type? I haven't looked at the code to see exactly how viable that is, so I could be completely off base.

**Comment by Fossil01** [comment]
Truth be told Documentaries as less of concern. So if you like X265 only thats fine too.

**Comment by thezoggy** [comment]
and most of those docu wont be pulled by sonarr in the first place due to naming conflicts with scrapers/unsupported format.

**Comment by thezoggy** [comment]
additionally.. more categories you add means you will hit max rss feed entries. which will roll stuff off quicker.. which means you need to be either more aggressive with the hits so you dont miss stuff. this is why the 'TV' category just isnt used (also you want to eliminate the noise of stuff you just would never want).

**Pull request closed without merging**
