### PR TITLE
Update the kickass url to https://kat.cr

### PR DESCRIPTION
**Pull request by kayone**

### CODE REVIEW

**Comment by Taloth** [comment]
Migration is already used. And why force ppl to https?

**Comment by kayone** [comment]
Kickass redirects to https, migration to https just saves a request and redirect.

**Comment by Taloth** [comment]
Ah, nevermind then... Except for the migration number of course.

**Comment by kayone** [comment]
I thought i rebased, I even had to change the number once. I'll check again.

**Comment by kayone** [comment]
I don't see another 89, is that what you mean?

**Comment by Taloth** [comment]
Markus has 89 for custom scripts. 
https://github.com/Sonarr/Sonarr/pull/552/files#diff-c18c50967e1a00514a4e616a1a6c3382R6

**Comment by kayone** [comment]
So what will happen when I merege this before custom scripts merge?

**Comment by Taloth** [comment]
Then your 90 migration will be executed first, and when markus merges in his stuff 89 will be executed. So the only requirement is that 90 doesn't affect 89 and vice versa.

And since it doesn't, feel free to merge it in.

**Comment by kayone** [comment]
I don't think it'll run 89 if db version is at 90. does it?

**Comment by Taloth** [comment]
it does, tried that out a year ago when we had like 4 internal PRs at the same time. But don't take my word for it, it takes 1 merge to test it locally.

**Comment by kayone** [comment]
yeah, just tested it and works.

**Pull request merged**
