### PR TITLE
New: Add option to import from any user's personal list

### PR DESCRIPTION
**Pull request by danimart1991**
#### Database Migration
NO

#### Description
Actually, Trakt Import List feature only allows personal list from authenticated user. This new option allow the user to set any user to import his lists.

### CODE REVIEW

**Comment by markus101** [comment]
@Qstick do you foresee any issues with this?

**Comment by danimart1991** [comment]
> @Qstick do you foresee any issues with this?

Hello @Qstick. This is not a fix. I want to import series from my wife's Trakt and my Trakt too. The problem is that the Import Lists -> List option only allows to import manual created Lists from a user, not its personal lists.

**Comment by Qstick** [comment]
What happens when you don't have access to the user's list that you are trying to access from the authed user?

**Comment by danimart1991** [comment]
> What happens when you don't have access to the user's list that you are trying to access from the authed user?

Hi @Qstick. I just test to change a public profile to private to check this.

Sonarr brings an error and in log you could see a HTTP 401 error.
image
image

**Comment by Qstick** [comment]
Seems ok to me @markus101, as long as you are good with above error handling.

**Pull request merged**
