### PR TITLE
Fix: Windows Long Path Support - Paths not allowed to be greater than 259 characters

### PR DESCRIPTION
**Pull request by Alanoll**
#### Database Migration
NO

#### Description
I changed the crafted string so it meets the segment limitations be still exceeded the old 255 character maximum.

#### Issues Fixed or Closed by this PR
#4877

### CODE REVIEW

**Comment by thezoggy** [comment]
the test was to check if long support is supported, so now your test is to see if its under the limit to know if its supported? this seems backwards

**Comment by Taloth** [comment]
No, he checks MAX_PATH properly now instead of doing a MAX_NAME test like we erroneously did.

**Comment by thezoggy** [comment]
he's changing from root + dir  to root + dir + dir and decreased each dir to less than max. i guess it should still trigger because root+ is still going to push it over the limit but just seemed odd of the change of 300->254

**Comment by Taloth** [comment]
It's coz on windows _with_ long path support. each path segment is still limited to 255. just the full path limit of 260 is removed.
So checking a path that's root+254+254+seperator pushes it well beyond 260. So we check if long path support is enabled, without running into the still existing 255 segment limit.

**Pull request merged**
