### PR TITLE
Delete data manually after finished seeding

### PR DESCRIPTION
**Pull request by margaale**
#### Database Migration
NO

#### Description
DS doesn't support deleting files when removing the torrent after it has finished seeding.

#### Issues Fixed or Closed by this PR

#1676

### CODE REVIEW

**Comment by margaale** [comment]
@Taloth Is there a way to determine if DeleteItemData has actually deleted the data?

**Comment by Taloth** [comment]
No, but that's trivial to add to that method.
But why would you need it? Don't you have to delete the torrent itself from the Syno itself regardless of that?

**Comment by margaale** [comment]
Yes i have and that it's what already did. Just asking cause if i delete the torrent, RemoveItem will never be called again and if files are still there they will never get deleted. Or at least that is what i understand from inspecting the code....

**Comment by Taloth** [comment]
You're correct, it would never get deleted if it went wrong at one point. But how often does that happen? If it failed to remove, it likely would've failed to import in the first place.
You could try handle things differently based on a `DeleteItemData` return value, such as not remove the torrent, but you'll end up having it retry every minute. That might be equally undesirable.
So my question is: Do you really need it? Or will you accept the risk that in some edge-case, you'll have leftovers in the download dir.

**Comment by margaale** [comment]
As a developer it bothers me that is not beiign atomic, as a user i guess i could live with that. So, let's keep it simple now and leave it as it is. If we get enough complaints from the users we can change it later.

**Pull request merged**
