### PR TITLE
Update to .NET 8

### PR DESCRIPTION
**Pull request by Gauvino**
#### Description
Overall update to .NET 8, need further testing and building test to see if everything working well.

If upgrading is simple as that I can do it on every other arr*

#### Changes
 - Update project to .NET 8
 - Update .NETFramework to 4.8.1
 - Update NuGet packages
 - Update Dockerfile from focal to jammy

### CODE REVIEW

**Comment by Gauvino** [comment]
After looking at everything and discover everything it's really not simple as that, if we wanted to make everything works will have to remake every dotnet repo from https://github.com/orgs/Servarr/repositories and much more

**Comment by markus101** [comment]
Not sure about the status of Servarr things, but commenting to say you need to rebase on top of develop, don’t merge develop into your branch, it will make a giant mess of things and will not be merged with merge commits.

**Comment by Gauvino** [comment]
> Not sure about the status of Servarr things, but commenting to say you need to rebase on top of develop, don’t merge develop into your branch, it will make a giant mess of things and will not be merged with merge commits.

Will remake the entire PR tomorrow the proper way

**Comment by bakerboy448** [comment]
Markus - the mono docker items can all be purged or updated to not need mono, no?

**Comment by Gauvino** [comment]
The question is does mono is still needed ?

**Pull request closed without merging**
