### PR TITLE
Parser: Remove 'Rakuv*' from the ends of release group names

### PR DESCRIPTION
**Pull request by desimaniac**
#### Database Migration
NO

#### Description
Removes any `-Rakuv*` combination from the ends of release group names. 

Examples: 
- [Blue.Bloods.S08E05.The.Forgotten.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb-Rakuv](https://nzbgeek.info/geekseek.php?guid=8e21042cb75c38d148cc8873c12f2cd3)
- [Lie.To.Me.S01E13.720p.BluRay.x264-SiNNERS-Rakuvfinhel
](https://nzbgeek.info/geekseek.php?guid=0454862a23f00972a3d454b3bdcb2328)
- [Who.is.America.S01E01.INTERNAL.720p.HDTV.x264-aAF-RakuvUS-Obfuscated](https://nzbgeek.info/geekseek.php?guid=b117e7f2c8f90771ea6b9f2520493e86)

Tested commit on a local build.

#### Log

https://pastebin.com/Chvf757d
```
19-3-11 06:16:14.9|Debug|QualityParser|Trying to parse quality for Blue.Bloods.S08E05.The.Forgotten.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb-Rakuv.mkv
19-3-11 06:16:14.9|Debug|Parser|Quality parsed: WEBDL-1080p v1
19-3-11 06:16:14.9|Debug|Parser|Release Group parsed: NTb
```

```
19-3-11 06:17:02.2|Debug|QualityParser|Trying to parse quality for Blue.Bloods.S08E05.The.Forgotten.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb-Rakuvfinhel.mkv
19-3-11 06:17:02.2|Debug|Parser|Quality parsed: WEBDL-1080p v1
19-3-11 06:17:02.2|Debug|Parser|Release Group parsed: NTb
```

https://pastebin.com/xYxv0Hau

```
19-3-11 13:03:56.6|Debug|QualityParser|Trying to parse quality for Who.is.America.S01E01.INTERNAL.720p.HDTV.x264-aAF-RakuvUS-Obfuscated.mkv
19-3-11 13:03:56.6|Debug|Parser|Quality parsed: HDTV-720p v1
19-3-11 13:03:56.6|Debug|Parser|Release Group parsed: aAF
```

#### Todos

- [x] Tests

#### Issues Fixed or Closed by this PR

* n/a

### CODE REVIEW

**Comment by Thirrian** [comment]
I've also seen stuff like `RakuvFin`.

**Comment by desimaniac** [comment]
You're right - just noticed them. A ton of `-Rakuvfinhel`. I'll update the PR.

**Comment by Thirrian** [comment]
Maybe a more generic approach should be taken for `rakuv*`?

````
jack.irish.s04e01.hdtv.x264-w4f-RakuvUS
yellowstone.2018.s01e04.internal.1080p.web.x264-bamboozle-RakuvDE
wentworth.s06e07.720p.ahdtv.x264-futv-RakuvFIN
Quantum.Leap.S02E18.Pool.Hall.Blues.BluRay.10Bit.1080p.AC3.H265-d3g-RakuvGEROV
````
Who knows what they'll think of in the future... :roll_eyes: 

Extra testcase (combo of `rakuv*` + `-obfuscated`):
````
Power.2014.S05E04.720p.WEB.H264-DEFLATE-RakuvFin-Obfuscated
Mystery.Road.S01E03.Chasing.Ghosts.WEBRip.576p-Rakuv-Obfuscated
````

**Comment by desimaniac** [comment]
Updated PR to handle any rakuv* combination.

**Comment by Taloth** [comment]
So, what does 'Rakuv' mean? And which indexer does it come from?

And please no .* wildcard, if you must use [a-z] or something like it.

**Comment by desimaniac** [comment]
Not sure. Maybe a group or indexer that reuploads NZBs. ¯\_(ツ)_/¯

Also regarding the regex, would this work?

```
^(.*?[-._ ](S\d+E\d+)[-._ ])|(-(Rakuv([a-z-]+)?|RP|1|NZBGeek|Obfuscated|Scrambled|sample|Pre|postbot|xpost))+$
```

Issue is that `Rakuv` can be alone or with `RakuvSUFFIX` or `RakuvSUFFIX-Anothertag`. 

Exames are mentioned above.

**Comment by Taloth** [comment]
`(-(Rakuv[a-z]*|RP`

> Issue is...

not an issue. look at the end: `)+$`

**Comment by desimaniac** [comment]
So the regex above is ok to submit ?

**Comment by desimaniac** [comment]
Pushed changes as requested!

**Comment by desimaniac** [comment]
Pushed changes as requested!

**Comment by desimaniac** [comment]
Thanks @Taloth !

**Pull request merged**
