### PR TITLE
Episode file editor

### PR DESCRIPTION
**Pull request by markus101**
@kayone @Taloth 

Not sure about the icon (we need to update to Font Awesome 4 to get some nicer ones):
https://www.dropbox.com/s/zrgousjbd6n7q8s/shot_150219_221448.png

Pretty simple editor:
https://www.dropbox.com/s/31sgxyi3xeywhra/shot_150219_221805.png?dl=0

Delete has a confirm, changing the quality does not since its reversible (without setting the recycling bin first).

### CODE REVIEW

**Comment by Taloth** [comment]
UI should be more like series editor, with a fixed footer.

**Comment by markus101** [comment]
So not a modal? I went with modal to keep it within the context of the series, instead of a separate page, since thats the style we typically use.

Wondering if it makes more sense to make the existing season grids editable via a toggle, that way the footer idea fits and the page context stays the same.

**Comment by Taloth** [comment]
Season grids don't have filenames and such. It's probably also complicated to make it work like that.
Personally I think this should be a full page with it's own route. Gives you more space to do exotic stuff in the future.

**Comment by markus101** [comment]
I think we could make the same argument about renaming. I'm leaning towards leaving it as-is and revisiting it during the UI upgrades, especially since modals + mobile aren't great (even in BS3).

We need a tie breaker from @kayone

**Pull request merged**
