### PR TITLE
Added Hebrew lanugage

### PR DESCRIPTION
**Pull request by rotem925**
#### Database Migration
NO

#### Description
Added support for Hebrew language.

#### Todos
- [x] Tests

#### Issues Fixed or Closed by this PR

* #2115

### CODE REVIEW

**Comment by rotem925** [comment]
I've made the same change for Radarr.

**Comment by markus101** [comment]
What was the purpose of this reversion? https://github.com/Radarr/Radarr/pull/1922

**Comment by rotem925** [comment]
I've added it to Radarr... what do you mean re-version? If you referring the remove of the iso.
It is just to disable the search by Hebrew language, since most of the movies/tv shows are still in english and does not come up in the search result of the torrents when they appear in Hebrew.

**Comment by markus101** [comment]
Sorry, I meant reverting. Does Radarr use the ISO Language when searching? We don't in Sonarr, but I want to make sure there wasn't a reason for us to also change that.

**Comment by rotem925** [comment]
@markus101 Yes, I the search results come in Hebrew in Radarr, that what it looked like. After I've removed the the iso and checked, then I could find torrents. If not the same for Sonarr, then this could stay... Thank you for taking care of this.

**Comment by markus101** [comment]
Merged in https://github.com/Sonarr/Sonarr/commit/7d21585f50cc57d4e6c6048584150a2114bb9530

**Pull request closed without merging**
