### PR TITLE
Synology Download Station client

### PR DESCRIPTION
**Pull request by OllieDay**
I've added a new torrent and usenet client for Synology Download Station.

Basic functionality appears to work so some feedback would be good!

I'm unsure about how to approach tests without duplicating all of the code for each client since they don't contain any logic. Any ideas?

Issue #347.

### CODE REVIEW

**Comment by tutipeti** [comment]
@OllieDay any chance you could also add `destination` as a parameter for creating the downloads? Then Sonarr could tell DS where to put the stuff. Would be really useful for me :) Thanks!

**Comment by tutipeti** [comment]
@OllieDay wow, that was super fast. Thanks! :)

**Comment by Taloth** [comment]
It's nice that DS is being worked on, it's been requested for some time now.

However, I do have some big comments:
- I see ALOT of logic in the `DownloadStationProxy` that doesn't belong there. The Proxy is only supposed to read the api, not do businesslogic. The Proxy shouldn't know anything about `DownloadClientItem` and such. So all that gotta be moved to `DownloadStation*` itself, that includes `Test` and `GetItems`. I suggest you look at the other download clients to see how it's done there.
- `DownloadStationUsenetClientFixture` is empty. So... write some tests. This is where the Proxy becomes important, coz when the Proxy is a thin wrapper around the api, you can mock against it and test all the businesslogic in `DownloadStationUsenetClient`.
- `DownloadStationUsenetClient` and `DownloadStationTorrentClient` both call the same `GetItems`, but who filters it? Like it is, and when you have both usenet & torrent clients added you would get dupes and all weird shit happening.
- We've been working on removing RestSharp, examples for how the new Proxies are being implemented can be found in https://github.com/Sonarr/Sonarr/pull/1166.
- Please tell me Download Station has some kind of Category support? If not, look at `Transmission` for an example of how it's dealt with there.

**Comment by OllieDay** [comment]
I'm having issues with remote path mapping since Synology uses "Shared Folders" which don't contain the full path, e.g. I have the Shared Folder "/volume1/Downloads" but the API returns only "Downloads" which causes the remote path mapping to fail.

Any workaround?

**Comment by Taloth** [comment]
Remote path mapping doesn't need the full path, just whatever the api reports. But it only applies when sonarr and download station doesn't run on the same syno, so I don't know how relevant it is. 

Alternatively, Isn't there an api to resolve the shared folder?

**Comment by OllieDay** [comment]
> Remote path mapping doesn't need the full path, just whatever the api reports. But it only applies when sonarr and download station doesn't run on the same syno, so I don't know how relevant it is.

This is my remote path mapping in Sonarr:

```
Host: nas.home
Remote path: Downloads
Local path: X:\
```

The following returns `Downloads` rather than `X:\` as it's `OsPathKind.Unknown`

`_remotePathMappingService.RemapRemoteToLocal("nas.home", new OsPath("Downloads"))`

> Alternatively, Isn't there an api to resolve the shared folder?

There is, but I wanted to avoid any extra complexity if possible.

**Comment by Taloth** [comment]
What what happens if Sonarr runs locally, how would it access 'Downloads'? I assumed it would be `/Downloads`.

**Comment by OllieDay** [comment]
It would be `/volume1/Downloads`. The API accepts download task creation using the full path, but queries return only `Downloads`.

Presumably the solution would be to set up a remote path mapping as follows:

```
Remote path: /volume1/Downloads
Local path: X:\
```

Then when retrieving a download task with destination `Downloads` use their API to resolve the full path as `/volume1/Downloads` before using the `RemotePathMappingService`.

Does that sound right?

**Comment by Taloth** [comment]
Yes, using the File Station api to resolve it to the full path would be best.

**Comment by foXaCe** [comment]
Hello, great job for this torrent client . you're going to merge this commit?

**Comment by cybrox** [comment]
Is there any more progress planned on this?
I would really like to switch to Sonarr from Sickrage, but the lack of feedback and the wrong states in the UI following this really keep me from doing this right now, even though it technically works with my own little blackhole script.

**Comment by OllieDay** [comment]
Been kinda busy lately but I'll try find time to work on it this week.

**Comment by Prime-Omega** [comment]
I would absolutely love to have this commit Keep up the good work, hoping to have it merged with my Sonarr soon!

**Comment by cybrox** [comment]
Awesome! Really appreciate your contribution @OllieDay

**Comment by elisiano** [comment]
👍 
I've been waiting for a while for this to make it to upstream so that I have no more excuses not to switch to sonarr.

**Comment by vfportero** [comment]
I was thinking about implement DS Download integration with Sonarr but I see that there's one almost ready.

Please @OllieDay, solve those conflicts and make this greatness can be added to master!

**Comment by cristiangauma** [comment]
Thank you for your time @OllieDay !! I hope you can get some spare time to finish it. Would be awesome to see this PR accepted on Master!.

**Comment by markus101** [comment]
Obsolete, see #1620

**Pull request closed without merging**
