### PR TITLE
Fixed: Use SVG for loading page icon

### PR DESCRIPTION
**Pull request by Snarkenfaugister**
Use SVG image for loading page icon instead of base64 png

#### Database Migration
NO

#### Description
Address issues raised in #4311

#### Issues Fixed or Closed by this PR
As above

### CODE REVIEW

**Comment by Taloth** [comment]
You have to embed the svg just like the png was. We don't want additional resource _loads_ for what's just a _loading screen_. The irony... :smile:

**Comment by Snarkenfaugister** [comment]
> 
> 
> You have to embed the svg just like the png was. We don't want additional resource _loads_ for what's just a _loading screen_. The irony... 😄

And here I was thinking that was the wrong way to do things. Reverted to the original. 😄

**Comment by Taloth** [comment]
Normally you'd be right, but since it's a loading screen you don't want to slow down the loading just to get a friggin icon loaded... for the loading screen.

**Comment by Taloth** [comment]
Isn't it possible to embed it via the base64?

**Pull request merged**
