### PR TITLE
lossless compression of images saved 14KB

### PR DESCRIPTION
**Pull request by Fish2**
Save Bandwidth and speed up website load time but lossless completion of all images.

doing this saved 14KB docent sound like much but why not

### CODE REVIEW

**Comment by Taloth** [comment]
Please... this is a waste of time. You saved 291 bytes effectively, not 14 KB. And that's like 0.8 % of the total traffic involved in fetching them, and 0.03 % vs the entire page load.
Prove to me that load time is faster or that any meaningful bandwidth is saved.

In development we call this premature optimization.

**Comment by markus101** [comment]
These inages we're previously run through pingo, I'm not sure what's was used here, but I know additional passes in pingo will save a bit more each pass (to a point), but Ithe savings is minimal.

https://github.com/Sonarr/Sonarr/pull/1606

**Comment by Fish2** [comment]
It has saved exactly 13.883KB but i don't know how many of the image files are used on the hosting side. but any optimization for free is surely a positive thing.

I used also used 
AdvPNG
PNGOUT

**Comment by Fish2** [comment]
just seen you use so you could use gulp-imagemin

**Pull request closed without merging**
